version: '3.8'

services:

  app:
    build: ./docker/web/php
    container_name: test_app
    restart: unless-stopped
    volumes:
      - ./src:/var/www
      - ./docker/web/php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini:ro
      - ./docker/web/php/php.ini:/usr/local/etc/php/php.ini-development:ro
      - ./docker/web/php/php.ini:/usr/local/etc/php/php.ini-production:ro
    working_dir: /var/www
    depends_on:
      - nginx
      - db
    networks:
      - test_network

  db:
    image: mysql:latest
    container_name: test_mysql
    command: ["--mysql-native-password=ON"]
    restart: unless-stopped
    ports:
      - "3307:3306"
    env_file:
      - ./docker/env/mysql.env
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - test_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: test_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=100000000
    depends_on:
      - db
    networks:
      - test_network

  nginx:
    image: nginx:latest
    container_name: test_nginx
    volumes:
      - ./src:/var/www
      - ./docker/web/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    ports:
      - "8080:80"
    env_file:
      - ./docker/env/nginx.env
    networks:
      - test_network

networks:
  test_network:
    driver: bridge
